eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9095/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: microservice-user
          uri: lb://utilisateur
          predicates:
            - Path=/utilisateur/**
          filters:
            - RewritePath=/utilisateur/(?<path>.*), /${path}
        
        - id: microservice-projet
          uri: lb://projet
          predicates:
            - Path=/projet/**
          filters:
            - RewritePath=/projet/(?<path>.*), /${path}
